### ISSUE TITLE
 SlickGrid -  jQuery is not defined

### ISSUE THREAD

**Issue by kaleming** [bokeh/SlickGrid#5]
Hi, I installed bokehjs module on vuejs:

- Installed BokehJS 2.4.3 using npm install @bokeh/bokehjs@2.4.3

- In the module where I want to embed the Bokeh plot: import { embed } from '@bokeh/bokehjs';

- To embed the plot after receiving a response from an Axios get request: embed.embed_item(response.data, 'myplot'); and include the JSX <div id='myplot' className="bk-root"></div> at the desired location.

However, I am getting this error on the browser:

```
ReferenceError: jQuery is not defined
    at node_modules/@bokeh/bokehjs/node_modules/@bokeh/slickgrid/slick.grid.js (slick.grid.js:19:11)
    at __require (chunk-HUBM7RA2.js?v=0bead79f:8:50)
    at node_modules/@bokeh/bokehjs/node_modules/@bokeh/slickgrid/index.js (index.js:4:20)
    at __require (chunk-HUBM7RA2.js?v=0bead79f:8:50)
    at data_table.js:5:35
```

**Comment by bryevdv** [comment]
cc @mattpap
